export const defaultProducts = [
  {
    slug: "character-collection",
    title: "Character Collection",
    category: "Stuffed Animals",
    featuredLabel: "Custom OEM",
    showInCollection: false,
    isFeatured: true,
    coverImage: "/uploads/seed/portfolio-1.jpg",
    media: [{ kind: "image", url: "/uploads/seed/portfolio-1.jpg" }],
    description: "Branded character plush set for a major North American retailer.",
    moq: "3,000 pieces per style",
    details:
      "This custom OEM project involved designing and manufacturing a complete line of branded character plush toys for one of North America's leading retail chains. Each character was developed from concept sketches to final production, ensuring brand consistency and child-safe materials throughout.",
    features: [
      "Custom pattern development from client artwork",
      "EN71 & ASTM F963 certified materials",
      "Embroidered facial details for durability",
      "Eco-friendly polyester fiber fill",
      "Individual polybag packaging with hang tags",
      "MOQ: 3,000 pieces per style",
    ],
    specs: [
      { label: "Size", value: "25 cm / 10 inches" },
      { label: "Material", value: "Super-soft plush fabric" },
      { label: "Fill", value: "100% recycled polyester" },
      { label: "Age", value: "3+ years" },
    ],
  },
  {
    slug: "fantasy-unicorn",
    title: "Fantasy Unicorn",
    category: "Stuffed Animals",
    featuredLabel: "ODM Design",
    showInCollection: false,
    isFeatured: true,
    coverImage: "/uploads/seed/portfolio-2.jpg",
    media: [{ kind: "image", url: "/uploads/seed/portfolio-2.jpg" }],
    description: "Pastel unicorn series with embroidered details and eco-friendly fill.",
    moq: "2,000 pieces per color",
    details:
      "Our in-house design team created this enchanting pastel unicorn series as part of our ODM catalog. Featuring intricate embroidered details on the horn, mane, and hooves, this collection showcases our capability to produce whimsical, high-quality plush toys ready for private labeling.",
    features: [
      "Original ODM design available for private label",
      "Multi-color embroidered horn and mane",
      "Glitter-infused fabric accents",
      "CPSIA compliant for the US market",
      "Gift-ready window box packaging",
      "MOQ: 2,000 pieces per color",
    ],
    specs: [
      { label: "Size", value: "30 cm / 12 inches" },
      { label: "Material", value: "Crystal super-soft plush" },
      { label: "Fill", value: "PP cotton, eco-friendly" },
      { label: "Age", value: "0+ years (infant safe)" },
    ],
  },
  {
    slug: "pet-pals-duo",
    title: "Pet Pals Duo",
    category: "Pet Plush Toys",
    featuredLabel: "Custom OEM",
    showInCollection: false,
    isFeatured: true,
    coverImage: "/uploads/seed/portfolio-3.jpg",
    media: [{ kind: "image", url: "/uploads/seed/portfolio-3.jpg" }],
    description: "Dog & cat plush pair for a European pet accessories brand.",
    moq: "5,000 pieces per set",
    details:
      "Developed for a leading European pet accessories brand, this adorable dog and cat duo was designed to complement their existing product line. The plush toys feature realistic proportions and premium materials, meeting strict EU safety standards for both children and pets.",
    features: [
      "Designed to match client's existing brand aesthetic",
      "CE marked, EN71 Parts 1-3 certified",
      "Reinforced stitching for pet-safe use",
      "Machine washable at 30°C",
      "Kraft paper eco-packaging",
      "MOQ: 5,000 pieces per set",
    ],
    specs: [
      { label: "Size", value: "20 cm / 8 inches each" },
      { label: "Material", value: "Short pile plush fabric" },
      { label: "Fill", value: "Hypoallergenic hollow fiber" },
      { label: "Age", value: "All ages" },
    ],
  },
  {
    slug: "pink-fantasy-plush",
    title: "Pink Fantasy Plush with Wings",
    category: "Stuffed Animals",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-1.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-1.jpg" }],
    description: "Dreamy pink plush toy with sparkly wings, perfect for imaginative play and gifting.",
    moq: "2,000 pcs",
    details:
      "A whimsical statement plush designed for premium gifting programs and themed retail collections. This style combines ultra-soft pastel fabric, decorative wing panels, and a lightweight structure suitable for display, gifting, and private-label customization.",
    features: [
      "Soft-touch premium plush exterior with decorative wing detailing",
      "Embroidery-friendly surfaces for custom logo placement",
      "Child-safe trims and hypoallergenic inner filling",
      "Color, accessory, and packaging customization available",
      "Suitable for seasonal campaigns and boutique gift ranges",
      "MOQ: 2,000 pieces",
    ],
    specs: [
      { label: "Size", value: "28 cm / 11 inches" },
      { label: "Material", value: "Velboa plush with sparkle accent panels" },
      { label: "Fill", value: "Hypoallergenic PP cotton" },
      { label: "Age", value: "3+ years" },
    ],
  },
  {
    slug: "white-dog-red-bow",
    title: "White Dog Plush with Red Bow",
    category: "Stuffed Animals",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-2.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-2.jpg" }],
    description: "Adorable sitting dog plush with a satin red bow — a timeless gift for all ages.",
    moq: "2,000 pcs",
    details:
      "This classic dog plush is ideal for evergreen gift assortments and promotional retail programs. Its clean silhouette, soft white fabric, and signature ribbon detail make it a versatile design for custom branding, packaging, and seasonal storytelling.",
    features: [
      "Classic sitting silhouette with satin ribbon accent",
      "Soft brushed plush fabric for a premium hand feel",
      "Custom neck ribbons, tags, and accessories supported",
      "Safe stitched detailing for long-term durability",
      "Retail-ready gift and souvenir positioning",
      "MOQ: 2,000 pieces",
    ],
    specs: [
      { label: "Size", value: "25 cm / 10 inches" },
      { label: "Material", value: "Short-pile plush fabric" },
      { label: "Fill", value: "Premium PP cotton" },
      { label: "Age", value: "3+ years" },
    ],
  },
  {
    slug: "gray-bunny-plush",
    title: "Gray Bunny Plush Toy",
    category: "Stuffed Animals",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-3.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-3.jpg" }],
    description: "Soft gray bunny with floppy ears, crafted with hypoallergenic filling.",
    moq: "2,000 pcs",
    details:
      "A soft nursery-friendly plush developed for baby gift sets, holiday programs, and lifestyle retailers. The relaxed floppy-ear design and muted color palette give this bunny a calm, premium look suited for both retail and branded collaborations.",
    features: [
      "Floppy-ear design with a gentle nursery aesthetic",
      "Soft-touch exterior with baby-friendly hand feel",
      "Customizable colors, embroidery, and hang tags",
      "Hypoallergenic filling for added comfort",
      "Suitable for infant gifting and plush collections",
      "MOQ: 2,000 pieces",
    ],
    specs: [
      { label: "Size", value: "27 cm / 10.6 inches" },
      { label: "Material", value: "Micro plush fabric" },
      { label: "Fill", value: "Hypoallergenic polyester fiber" },
      { label: "Age", value: "0+ years" },
    ],
  },
  {
    slug: "classic-teddy-bear",
    title: "Classic Brown Teddy Bear",
    category: "Stuffed Animals",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-4.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-4.jpg" }],
    description: "A timeless teddy bear with premium plush fabric and ribbon accent.",
    moq: "3,000 pcs",
    details:
      "This heritage teddy bear style is designed for timeless retail appeal. With a balanced shape, premium plush texture, and elegant ribbon accessory, it works well for brand anniversaries, gift campaigns, and traditional toy ranges.",
    features: [
      "Classic teddy-bear proportions with premium ribbon trim",
      "High-density plush fabric for a fuller appearance",
      "Custom ribbon colors and private-label options available",
      "Embroidered facial details for safety and durability",
      "Ideal for gift, souvenir, and heritage toy programs",
      "MOQ: 3,000 pieces",
    ],
    specs: [
      { label: "Size", value: "30 cm / 12 inches" },
      { label: "Material", value: "Premium shaggy plush" },
      { label: "Fill", value: "Recycled polyester fiber" },
      { label: "Age", value: "3+ years" },
    ],
  },
  {
    slug: "baby-elephant-mouse",
    title: "Baby Elephant with Little Mouse",
    category: "Stuffed Animals",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-5.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-5.jpg" }],
    description: "Charming elephant and mouse duo — a unique design perfect for nursery décor.",
    moq: "2,500 pcs",
    details:
      "A storytelling-driven plush concept pairing a baby elephant with a tiny mouse companion. This dual-character format is ideal for nursery collections, themed decor, and gift programs where a distinctive silhouette helps products stand out on shelf.",
    features: [
      "Dual-character concept for added collectible appeal",
      "Soft pastel palette suited to nursery and gifting segments",
      "Detailed applique and embroidery customization options",
      "Designed for boutique retail and decorative plush lines",
      "Branding, packaging, and accessory customization supported",
      "MOQ: 2,500 pieces",
    ],
    specs: [
      { label: "Size", value: "26 cm / 10.2 inches" },
      { label: "Material", value: "Velboa plush with applique accents" },
      { label: "Fill", value: "Soft PP cotton" },
      { label: "Age", value: "0+ years" },
    ],
  },
  {
    slug: "panda-plush",
    title: "Panda Bear Plush Toy",
    category: "Stuffed Animals",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-6.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-6.jpg" }],
    description: "Classic black and white panda, irresistibly soft and child-safe.",
    moq: "2,000 pcs",
    details:
      "A retail-ready panda plush with broad international appeal. The clean black-and-white palette, rounded body shape, and soft-touch finish make it a strong candidate for zoo shops, gift retailers, and mass-market toy collections.",
    features: [
      "Iconic panda styling with soft rounded proportions",
      "Child-safe embroidered facial construction",
      "Flexible sizing and accessory customization available",
      "Suitable for souvenirs, promotions, and plush collections",
      "Export-ready materials and packaging support",
      "MOQ: 2,000 pieces",
    ],
    specs: [
      { label: "Size", value: "24 cm / 9.5 inches" },
      { label: "Material", value: "Crystal super-soft plush" },
      { label: "Fill", value: "Eco-friendly PP cotton" },
      { label: "Age", value: "3+ years" },
    ],
  },
  {
    slug: "kawaii-keychain",
    title: "Kawaii Animal Keychain",
    category: "Plush Keychains",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-7.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-7.jpg" }],
    description: "Mini plush keychain accessory, colorful and trendy for Gen Z consumers.",
    moq: "5,000 pcs",
    details:
      "A compact plush accessory designed for impulse purchase, event merchandise, and branded giveaways. Its small footprint, vibrant styling, and collectible character make it ideal for youth-oriented campaigns and trend-driven product drops.",
    features: [
      "Mini-format plush with attached keychain hardware",
      "Excellent for promotions, blind-box lines, and gifting",
      "Supports custom colorways, mascots, and packaging",
      "Lightweight design optimized for accessory programs",
      "Appeals to youth, lifestyle, and pop-culture markets",
      "MOQ: 5,000 pieces",
    ],
    specs: [
      { label: "Size", value: "10 cm / 4 inches" },
      { label: "Material", value: "Short-pile plush with metal keyring" },
      { label: "Fill", value: "Lightweight polyester fiber" },
      { label: "Age", value: "8+ years" },
    ],
  },
  {
    slug: "cat-pillow-plush",
    title: "Cat Pillow Plush",
    category: "Plush Pillows",
    featuredLabel: "",
    showInCollection: true,
    isFeatured: false,
    coverImage: "/uploads/seed/collection-8.jpg",
    media: [{ kind: "image", url: "/uploads/seed/collection-8.jpg" }],
    description: "Round cat-shaped plush pillow, perfect blend of comfort and cute design.",
    moq: "2,000 pcs",
    details:
      "A comfort-focused plush pillow combining decorative appeal with everyday usability. The rounded cat silhouette works well for lifestyle gifting, home décor assortments, and branded comfort collections aimed at teens and young adults.",
    features: [
      "Hybrid plush-and-pillow concept for décor and comfort use",
      "Large printable surface for branding or character artwork",
      "Soft supportive fill for lounge and bedroom settings",
      "Custom fabrics, expressions, and packaging available",
      "Ideal for lifestyle retail and gift programs",
      "MOQ: 2,000 pieces",
    ],
    specs: [
      { label: "Size", value: "35 cm / 13.8 inches" },
      { label: "Material", value: "Velboa plush fabric" },
      { label: "Fill", value: "Supportive PP cotton blend" },
      { label: "Age", value: "3+ years" },
    ],
  },
];

export const defaultBlogs = [
  {
    slug: "how-to-choose-the-right-plush-toy-manufacturer",
    title: "How to Choose the Right Plush Toy Manufacturer for Your Brand",
    excerpt:
      "Key factors to evaluate when selecting an OEM partner — from MOQs and material quality to certifications and lead times.",
    shortExcerpt: "Key factors to evaluate when selecting an OEM partner.",
    publishedAt: "2026-03-15T00:00:00.000Z",
    category: "Industry Guide",
    readTime: "5 min read",
    coverImage: "/uploads/seed/blog-1.jpg",
    content: [
      "Choosing the right plush toy manufacturer is one of the most critical decisions for any brand entering the custom plush market. The right partner can make the difference between a successful product launch and a costly mistake.",
      "First, evaluate the manufacturer's experience and specialization. A company with decades of experience in plush manufacturing will understand the nuances of different materials, stitching techniques, and safety standards. Look for manufacturers who have worked with well-known brands and can provide references.",
      "Material quality is paramount. The best manufacturers use high-grade, hypoallergenic fabrics and fillings that meet international safety standards like EN71, ASTM F963, and CPSIA. Ask for material certifications and sample products to assess the quality firsthand.",
      "MOQ (Minimum Order Quantity) flexibility is important for new brands. Some manufacturers require orders of 5,000+ units, while others like YCNST offer lower MOQs to help brands test the market before committing to large production runs.",
      "Lead times and communication are often overlooked but crucial factors. A reliable manufacturer should provide clear timelines, regular updates, and responsive communication throughout the production process.",
      "Finally, consider the manufacturer's design capabilities. The best partners offer in-house design teams that can help refine your concepts, create prototypes, and suggest improvements based on their manufacturing expertise.",
    ],
    likesCount: 24,
    comments: [
      {
        name: "Sarah Chen",
        text: "Great insights! This really helped us choose the right manufacturer for our brand.",
        createdAt: "2026-03-16T00:00:00.000Z",
      },
      {
        name: "James Wilson",
        text: "Very informative article. Would love to see more content like this.",
        createdAt: "2026-03-17T00:00:00.000Z",
      },
    ],
  },
  {
    slug: "2026-plush-toy-trends",
    title: "2026 Plush Toy Trends: What's Selling in North America & Europe",
    excerpt:
      "From oversized comfort plush to eco-friendly collections, discover the trends shaping the custom toy market this year.",
    shortExcerpt: "Discover the trends shaping the custom toy market this year.",
    publishedAt: "2026-02-28T00:00:00.000Z",
    category: "Trends",
    readTime: "4 min read",
    coverImage: "/uploads/seed/blog-2.jpg",
    content: [
      "The plush toy industry continues to evolve rapidly, with 2026 bringing exciting new trends that brands and retailers need to understand to stay competitive.",
      "Oversized comfort plush toys are dominating the market. Consumers are gravitating toward large, huggable plush items that serve as both toys and home décor. These jumbo plush pieces range from 24 to 48 inches and have seen a 40% increase in demand over the past year.",
      "Eco-friendly and sustainable plush toys are no longer a niche — they're becoming the standard. Brands using recycled polyester fillings, organic cotton exteriors, and biodegradable packaging are seeing premium pricing acceptance from environmentally conscious consumers.",
      "Character collaborations and licensed plush remain strong, but there's a growing market for original, artisan-designed characters. Small brands are finding success with unique, story-driven plush characters that connect emotionally with collectors.",
      "Interactive and sensory plush toys incorporating weighted elements, different textures, and calming features are trending, particularly in the wellness and therapeutic toy categories.",
      "The collectible mini-plush segment continues to grow, with keychain-sized plush items becoming popular accessories among Gen Z consumers. These items serve as affordable entry points for new brands.",
    ],
    likesCount: 18,
    comments: [],
  },
  {
    slug: "sustainability-in-plush-manufacturing",
    title: "Sustainability in Plush Manufacturing: Our Eco-Friendly Journey",
    excerpt:
      "How YCNST is leading the way with recycled fillings, organic fabrics, and carbon-neutral shipping practices.",
    shortExcerpt: "How YCNST is leading the way with sustainable practices.",
    publishedAt: "2026-02-10T00:00:00.000Z",
    category: "Sustainability",
    readTime: "6 min read",
    coverImage: "/uploads/seed/blog-3.jpg",
    content: [
      "At YCNST, sustainability isn't just a buzzword — it's a fundamental part of our manufacturing philosophy. Over the past five years, we've transformed our production processes to minimize environmental impact while maintaining the highest quality standards.",
      "Our journey began with material sourcing. We now offer recycled polyester filling made from post-consumer plastic bottles. Each plush toy can contain the equivalent of 5-15 recycled bottles, depending on size, diverting thousands of bottles from landfills annually.",
      "Organic cotton and bamboo fiber fabrics have become standard options in our material library. These sustainable alternatives provide the same soft, luxurious feel that consumers expect while reducing pesticide use and water consumption in the supply chain.",
      "Our factory has implemented a comprehensive waste reduction program. Fabric scraps are sorted and recycled into new filling material or donated to local craft programs. We've reduced manufacturing waste by 60% since 2022.",
      "Carbon-neutral shipping is now available for all international orders. We partner with certified carbon offset programs and optimize shipping routes to minimize our transportation footprint.",
      "Looking ahead, we're investing in solar panels for our production facility and exploring plant-based dyes to further reduce our environmental impact. Our goal is to achieve carbon-neutral manufacturing by 2028.",
    ],
    likesCount: 11,
    comments: [],
  },
];
